import Foundation

struct Localizer {
    static func text(_ key: String, language: AppLanguage) -> String {
        dictionary[key]?[language] ?? dictionary[key]?[.en] ?? key
    }

    private static let dictionary: [String: [AppLanguage: String]] = [
        "app.title": [.zhHans: "BeforeInstall", .en: "BeforeInstall"],
        "app.subtitle": [.zhHans: "拖入任意文件，生成安装前与运行行为风险报告。", .en: "Drop any file to generate pre-install and runtime risk insights."],
        "app.primarySupport": [.zhHans: "重点支持 .app/.pkg/.dmg；其他文件提供基础线索分析。", .en: "Best support: .app/.pkg/.dmg; other files receive baseline signal analysis."],
        "drop.hint": [.zhHans: "拖拽一个或多个文件到这里", .en: "Drop one or more files here"],
        "drop.support": [.zhHans: "支持任意文件；可一次性多选批量分析（优先深度支持 .app / .pkg / .dmg）", .en: "Any file is accepted; multi-file batch analysis is supported (best support for .app / .pkg / .dmg)."],
        "drop.pick": [.zhHans: "选择文件（可多选）", .en: "Choose Files"],
        "status.idle": [.zhHans: "等待导入文件", .en: "Waiting for a file"],
        "status.done": [.zhHans: "分析完成", .en: "Analysis completed"],
        "status.filePickerFailed": [.zhHans: "文件选择失败", .en: "File selection failed"],
        "status.busy": [.zhHans: "当前有分析任务正在运行，请先等待完成。", .en: "An analysis task is already running. Please wait."],
        "warning.partial": [.zhHans: "部分信息无法获取，详见技术详情。", .en: "Some fields are unavailable. Check technical details."],
        "permissions.banner.title": [.zhHans: "权限引导", .en: "Permission Guidance"],
        "permissions.banner.body": [.zhHans: "检测到“完全磁盘访问”可能未授予。建议先完成授权，以提升文件读取与差分稳定性。", .en: "Full Disk Access appears missing. Grant it first to improve file access and diff stability."],
        "permissions.banner.request": [.zhHans: "立即请求权限", .en: "Request Permissions Now"],
        "permissions.banner.fullDisk": [.zhHans: "打开完全磁盘访问", .en: "Open Full Disk Access"],
        "permissions.banner.dismiss": [.zhHans: "暂不提示", .en: "Dismiss"],
        "settings.title": [.zhHans: "设置", .en: "Settings"],
        "settings.language": [.zhHans: "界面语言", .en: "Language"],
        "settings.appearance": [.zhHans: "外观模式", .en: "Appearance"],
        "settings.fontScaleTitle": [.zhHans: "字体大小", .en: "Font Size"],
        "settings.fontScaleHint": [
            .zhHans: "调整应用内文字与关键布局尺寸；字号较大时会自动切换到更易读布局。",
            .en: "Adjust in-app text and key layout sizing. Larger text automatically switches to a more readable layout."
        ],
        "settings.showWelcome": [.zhHans: "启动时显示欢迎与权限引导", .en: "Show welcome and permission guide on launch"],
        "settings.allowNonApp": [.zhHans: "允许动态执行非 .app 文件（高风险，默认关闭）", .en: "Allow dynamic execution for non-.app files (risky, off by default)"],
        "settings.dynamicPrompt": [.zhHans: "动态分析前显示安全提示", .en: "Show safety prompt before dynamic analysis"],
        "settings.requestPermissionNow": [.zhHans: "立即请求辅助功能权限", .en: "Request Accessibility Permission"],
        "settings.openFullDisk": [.zhHans: "打开完全磁盘访问", .en: "Open Full Disk Access"],
        "settings.requestPermissionsNow": [.zhHans: "立即请求权限（推荐）", .en: "Request Permissions Now (Recommended)"],
        "settings.permissionsOnlyWhenMissing": [.zhHans: "仅在明确未授权时显示“去授权”按钮（当前仅检查完整磁盘访问）。", .en: "Authorize buttons are shown only when permission is explicitly not granted (currently Full Disk Access only)."],
        "settings.experimental": [.zhHans: "动态分析为实验性受限观察模式，不是完整恶意软件沙箱。", .en: "Dynamic analysis is an experimental restricted observation mode, not a full malware sandbox."],
        "settings.backgroundLaunch": [.zhHans: "动态分析时尝试隐藏 App 窗口", .en: "Try hiding app window in dynamic analysis"],
        "settings.backgroundLaunchHint": [
            .zhHans: "启用后会用 DYLD_INSERT_LIBRARIES 注入 no_window.dylib 启动目标 App；手动交互模式会忽略该设置。",
            .en: "When enabled, dynamic analysis launches the target app with DYLD_INSERT_LIBRARIES + no_window.dylib. Manual interaction mode ignores this setting."
        ],
        "controls.analysisMode": [.zhHans: "分析模式", .en: "Analysis Mode"],
        "controls.depth": [.zhHans: "分析深度", .en: "Depth"],
        "controls.clean": [.zhHans: "清理临时分析环境", .en: "Clean Temporary Workspaces"],
        "controls.experimental": [.zhHans: "实验性功能：动态分析不能保证完全隔离。", .en: "Experimental: dynamic analysis cannot guarantee full isolation."],
        "controls.endInteraction": [.zhHans: "结束交互并完成动态分析", .en: "Finish Interaction and Stop Dynamic Analysis"],
        "controls.deepGuide": [
            .zhHans: "深度动态分析进行中：请在目标应用窗口中完成你想测试的操作，然后点击“结束交互并完成动态分析”。",
            .en: "Deep dynamic analysis is running: interact with the target app, then click 'Finish Interaction and Stop Dynamic Analysis'."
        ],
        "summary.title": [.zhHans: "总结", .en: "Summary"],
        "dynamic.section": [.zhHans: "动态分析", .en: "Dynamic Analysis"],
        "dynamic.logs": [.zhHans: "会话日志", .en: "Session Logs"],
        "dynamic.summary": [.zhHans: "动态分析概览", .en: "Dynamic Summary"],
        "dynamic.processTree": [.zhHans: "进程树", .en: "Process Tree"],
        "dynamic.flatList": [.zhHans: "扁平列表", .en: "Flat List"],
        "dynamic.fsChanges": [.zhHans: "文件系统变更", .en: "File System Changes"],
        "dynamic.network": [.zhHans: "网络活动", .en: "Network Activity"],
        "dynamic.timeline": [.zhHans: "行为时间线", .en: "Behavior Timeline"],
        "dynamic.showDetails": [.zhHans: "查看详情", .en: "Show Details"],
        "dynamic.createdFiles": [.zhHans: "新增文件", .en: "Created Files"],
        "dynamic.modifiedFiles": [.zhHans: "修改文件", .en: "Modified Files"],
        "dynamic.deletedFiles": [.zhHans: "删除文件", .en: "Deleted Files"],
        "dynamic.noDiff": [.zhHans: "无差分结果。", .en: "No file diff result."],
        "dynamic.noNetwork": [.zhHans: "未观察到明显网络连接或结果不完整。", .en: "No obvious network connections observed or data is partial."],
        "dynamic.noTimeline": [.zhHans: "无行为时间线数据。", .en: "No behavior timeline data."],
        "dynamic.noTree": [.zhHans: "未获取到完整进程树（可能受权限限制）。", .en: "Process tree is unavailable (possibly due to permissions)."],
        "dynamic.diffIncomplete": [.zhHans: "差分结果不完整", .en: "Diff result is incomplete"],
        "risk.title": [.zhHans: "风险等级", .en: "Risk"],
        "risk.score": [.zhHans: "评分", .en: "Score"],
        "warnings.title": [.zhHans: "部分信息无法获取", .en: "Partial Data Warnings"],
        "details.title": [.zhHans: "技术详情", .en: "Technical Details"],
        "basic.title": [.zhHans: "基础信息", .en: "Basic Information"],
        "history.title": [.zhHans: "分析历史", .en: "Analysis History"],
        "history.empty": [.zhHans: "暂无历史记录", .en: "No history yet"],
        "history.open": [.zhHans: "查看", .en: "Open"],
        "history.rerun": [.zhHans: "重跑", .en: "Re-run"],
        "history.delete": [.zhHans: "删除", .en: "Delete"],
        "actions.export": [.zhHans: "导出报告", .en: "Export Report"],
        "actions.exportText": [.zhHans: "纯文本摘要", .en: "Text Summary"],
        "actions.copySummary": [.zhHans: "复制摘要", .en: "Copy Summary"],
        "actions.copySHA": [.zhHans: "复制 SHA256", .en: "Copy SHA256"],
        "actions.copySignature": [.zhHans: "复制签名", .en: "Copy Signature"],
        "actions.copyDetails": [.zhHans: "复制技术详情", .en: "Copy Technical Details"],
        "actions.copyTimeline": [.zhHans: "复制时间线", .en: "Copy Timeline"],
        "actions.copyNetwork": [.zhHans: "复制网络摘要", .en: "Copy Network"],
        "actions.exportDiagnostics": [.zhHans: "导出诊断日志", .en: "Export Diagnostics"],
        "issues.title": [.zhHans: "失败原因与建议", .en: "Failure Reasons & Suggestions"],
        "issues.suggestionPrefix": [.zhHans: "建议：", .en: "Suggestion: "],
        "menu.settings": [.zhHans: "设置...", .en: "Settings..."],
        "menu.openSettings": [.zhHans: "打开设置...", .en: "Open Settings..."],
        "menu.about": [.zhHans: "关于 BeforeInstall", .en: "About BeforeInstall"],
        "menu.view": [.zhHans: "视图", .en: "View"],
        "menu.help": [.zhHans: "帮助", .en: "Help"],
        "menu.welcome": [.zhHans: "欢迎与权限引导", .en: "Welcome & Permissions"],
        "menu.openFullDisk": [.zhHans: "打开“完全磁盘访问”", .en: "Open Full Disk Access"],
        "menu.openAccessibility": [.zhHans: "打开“辅助功能”", .en: "Open Accessibility"],
        "menu.openAutomation": [.zhHans: "打开“自动化”", .en: "Open Automation"],
        "welcome.title": [.zhHans: "欢迎使用 BeforeInstall", .en: "Welcome to BeforeInstall"],
        "welcome.subtitle": [.zhHans: "这是一个安装前与受限运行行为分析工具，帮助你在执行前理解软件风险。", .en: "This is a pre-install and restricted runtime analysis tool to help you understand software risk before execution."],
        "welcome.capability": [.zhHans: "应用能力：静态分析签名/权限/脚本与结构线索，并在受限环境做动态行为观察。", .en: "Capabilities: static analysis of signatures/permissions/scripts/structure, plus restricted dynamic behavior observation."],
        "welcome.permissionNote": [.zhHans: "权限说明：macOS 不允许应用一次性自动授予“完全磁盘访问”等高权限。当前版本提供跳转入口，由你手动授权。", .en: "Permission note: macOS does not allow one-shot automatic granting of high privileges such as Full Disk Access. This version provides direct links for manual authorization."],
        "welcome.permissionHealth": [.zhHans: "权限健康检查", .en: "Permission Health"],
        "welcome.permissionGrantedMark": [.zhHans: "已授权", .en: "Granted"],
        "welcome.permissionMissingMark": [.zhHans: "未授权", .en: "Not Granted"],
        "welcome.permissionUnknownMark": [.zhHans: "未检测", .en: "Unknown"],
        "welcome.permissionAction": [.zhHans: "去授权", .en: "Authorize"],
        "welcome.permissionAccessibilityTitle": [.zhHans: "辅助功能 (Accessibility)", .en: "Accessibility"],
        "welcome.permissionAccessibilityImpact": [.zhHans: "影响：动态交互引导与交互检测能力。", .en: "Impact: dynamic interaction guidance and interaction-related checks."],
        "welcome.permissionFullDiskTitle": [.zhHans: "完全磁盘访问 (Full Disk Access)", .en: "Full Disk Access"],
        "welcome.permissionFullDiskImpact": [.zhHans: "影响：关键目录读取与文件差分完整性。", .en: "Impact: key path reads and file diff completeness."],
        "welcome.permissionAutomationTitle": [.zhHans: "自动化 (Automation)", .en: "Automation"],
        "welcome.permissionAutomationImpact": [.zhHans: "影响：跨应用控制能力（如未来扩展自动化分析）。", .en: "Impact: cross-app control capability for future automation workflows."],
        "welcome.permissionDetectionNote": [.zhHans: "说明：权限状态会在窗口激活时自动刷新；完全磁盘访问为启发式检测。", .en: "Note: permission status refreshes when the window becomes active; Full Disk Access is heuristic."],
        "welcome.permissionAlreadyGrantedIntro": [.zhHans: "已检测到完整磁盘访问权限。以下仅显示产品简介，你可以直接继续使用。", .en: "Full Disk Access appears granted. The section below is informational only and you can continue directly."],
        "welcome.permissionGranted": [.zhHans: "辅助功能权限已授予（或已存在）。其余权限请在系统设置确认。", .en: "Accessibility permission is already granted. Please confirm the rest in System Settings."],
        "welcome.permissionRequested": [.zhHans: "已触发辅助功能权限弹窗。请在系统设置中完成授权。", .en: "Accessibility prompt triggered. Please complete authorization in System Settings."],
        "welcome.openFullDisk": [.zhHans: "前往“完全磁盘访问”", .en: "Go to Full Disk Access"],
        "welcome.openedSystemSettings": [.zhHans: "已打开系统设置，请在“完全磁盘访问”中完成授权。", .en: "System Settings opened. Complete authorization in Full Disk Access."],
        "welcome.openAccessibility": [.zhHans: "前往“辅助功能”", .en: "Go to Accessibility"],
        "welcome.openAutomation": [.zhHans: "前往“自动化”", .en: "Go to Automation"],
        "welcome.continue": [.zhHans: "继续使用", .en: "Continue"],
        "welcome.dontShowAgain": [.zhHans: "下次启动不再显示", .en: "Don't show again"]
    ]
}
